### ISSUE TITLE
Define loot pull regions with WorldGuard

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ContainerFaker#8]
Replace the existing hardcoded regions with WorldGuard regions. Define the worldguard regions to pull from with a list in the config.yml that also identifies which blocks are associated with that loot pull.

## Example:
```
regionname:
    block1: 
        type: DROPPER
        commands:
        - playsound minecraft:entity.villager.trade ambient 1.0 1.0
        - summon minecraft:zombie ~ ~ 5
    block2:
        type: DISPENSER
        commands:
        - playsound minecraft:entity.villager.trade ambient 1.0 1.0
        - summon minecraft:zombie ~ ~ 5
```
