### ISSUE TITLE
Allow commands to be run when opening a container

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ContainerFaker#9]
Add a method for configurable commands that can be run when a container is opened. Allow to be run as player or as console

## Example:
```
regionname:
    block1: 
        type: DROPPER
        commands:
            as-player:
            - playsound minecraft:entity.villager.trade ambient 1.0 1.0
            - summon minecraft:zombie ~ ~ 5
            as-console:
            - give {player} minecraft:stone 5
    block2:
        type: DISPENSER
        commands:
            as-player:
            - playsound minecraft:entity.villager.trade ambient 1.0 1.0
            - summon minecraft:zombie ~ ~ 5
            as-console:
            - give {player} minecraft:stone 5
```
